import "./globals.css";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import Navbar from "@/components/navbar";
import { Toaster } from "@/components/ui/toaster"
type Props = {
  children: React.ReactNode;
}
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props: Props) {
  
  const { children } = props;
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
          <div className="flex flex-col gap-6 px-44 py-12">
            <Navbar />
            <Toaster />
            <div>
              {children}
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
